name: vocaday_app
description: "An English Vocabulary learing app."
publish_to: "none"

version: 1.0.6+7

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.0
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_card_swiper: ^7.0.0
  flutter_heatmap_calendar: ^1.0.5
  flutter_local_notifications: ^16.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  get_it: ^7.6.4
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.4
  in_app_review: ^2.0.9
  in_app_update: ^4.2.2
  intl: ^0.18.1
  like_button: ^2.0.5
  logger: ^2.0.2+1
  lottie: ^3.1.0
  path: ^1.8.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_1024.png"
  adaptive_icon_background: "#ff3b47de"

flutter_gen:
  output: lib/app/constants/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/translations/
    - assets/data/
    - assets/sounds/

  fonts:
    # - family: Roboto_300 # Light - w300
    #   fonts:
    #     - asset: assets/fonts/Roboto-Light.ttf
    #     - asset: assets/fonts/Roboto-LightItalic.ttf
    #       style: italic
    - family: Roboto # Regular - w400
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-RegularItalic.ttf
          style: italic
    # - family: Roboto_500 # Medium - w500
    #   fonts:
    #     - asset: assets/fonts/Roboto-Medium.ttf
    #     - asset: assets/fonts/Roboto-MediumItalic.ttf
    #       style: italic
    # - family: Roboto_700 # Bold - w700
    #   fonts:
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #     - asset: assets/fonts/Roboto-BoldItalic.ttf
    #       style: italic
